- name: H3C Backup Playbook
  hosts: all
  gather_facts: no

  tasks:
    - name: Konfiqurasiyani oxu
      cli_command:
        command: display current-configuration
      vars:
        ansible_command_timeout: 300
      register: switch_config

    - name: Backup qovlugunu yarat
      file:
        path: "/mnt/win_backups"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Fayli Semaphore serverinde saxla
      copy:
        content: "{{ switch_config.stdout }}"
        # Burada faylı birbaşa mount olunmuş Windows qovluğuna yazırıq
        dest: "/mnt/win_backups/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d') }}.cfg"
      delegate_to: localhost
