---
- name: Hazirliq ve Backup
  hosts: all
  gather_facts: no

  tasks:
    - name: Paramiko-nun qurasdirildigindan emin olun
      pip:
        name: paramiko
        state: present
      delegate_to: localhost
      run_once: true

    - name: Konfiqurasiyani oxu
      cli_command:
        command: display current-configuration
      register: switch_config

    - name: Fayli /tmp qovluguna yaz
      copy:
        content: "{{ switch_config.stdout }}"
        dest: "/tmp/{{ inventory_hostname }}.cfg"
      delegate_to: localhost
