---
- name: H3C Backup Playbook
  hosts: all
  gather_facts: no

  tasks:
    - name: Konfiqurasiyani oxu
      cli_command:
        command: display current-configuration
      vars:
        # Bu hissə Ansible-a 5 dəqiqəyə qədər gözləməyə icazə verir
        ansible_command_timeout: 300
      register: switch_config

    - name: Backup qovlugunu yarat
      file:
        path: "/tmp/h3c_backups"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Fayli Semaphore serverinde saxla
      copy:
        content: "{{ switch_config.stdout }}"
        dest: "/tmp/h3c_backups/{{ inventory_hostname }}_{{ ansible_date_time.date | default('today') }}.cfg"
      delegate_to: localhost
