[h3c_switches]
switch1 ansible_host=10.10.190.11

[h3c_switches:vars]
ansible_user=admin
ansible_password=adminsai20
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=comware
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
